name: ecommerce_app
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'



dependencies:
  flutter:
    sdk: flutter


  
  
  #local Stroage
  shared_preferences: ^2.3.1
  flutter_secure_storage:

  internet_connection_checker: ^1.0.0+1
  http: ^1.0.0
  equatable: ^2.0.3
  dartz: ^0.10.0
  flutter_bloc: ^8.0.0
  image_picker: ^0.8.6
  
  #state management 
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  get_it: ^7.7.0

  #ui 
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_easyloading: ^3.0.5


  dev: ^1.0.0

  analyzer: ^6.4.1
  http_parser: ^4.0.2
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0
  test: ^1.16.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  build_runner: ^2.4.9
  matcher: ^0.12.16+1
  bloc_test: ^9.1.7

  json_serializable: ^6.8.0
  
  intl: ^0.19.0





flutter:

  
  
  
  uses-material-design: true

  assets:
    - assets/
  


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Syne
      fonts: 
        - asset: fonts/Syne-VariableFont_wght.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
